---
dependencies: []
galaxy_info:
  namespace: dfl_technology
  role_name: common
  author: jonaugustine
  description: Shared role for FreeTAKServer
  company: DFL-Technology
  license: license (EPL-2.0)
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
      - 16.04
      - 18.04
      - 20.04
  galaxy_tags:
    - freetakserver
    - atak
    - tak
    - takserver
    - common
