---
- name: Template config.py config file.
  template:
    src: config.py.j2
    dest: '{{ fts_ui_packages_path }}/config.py'
    mode: 0644

- name: Copy systemctl replacement workaround.
  copy:
    src: systemctl3.py
    dest: /usr/local/bin/systemctl
    mode: 0755

- name: Template freetakserver_ui.service unit file
  template:
    src: freetakserver_ui.service.j2
    dest: /lib/systemd/system/freetakserver_ui.service
    mode: 0644
  notify: 
    # - reload freetakserver_ui
    - enable freetakserver_ui
    - set freetakserver_ui state
