---
- name: Check if FreeTAKServer-UI is installed
  shell: >
    set -o pipefail &&
    {{ pip3 }} list |
    grep FreeTAKServer-UI
  args:
    warn: no
    executable: /bin/bash
  register: result
  changed_when: false
  ignore_errors: yes

- name: Install FreeTAKServer-UI apt dependencies
  apt:
    name: "{{ fts_ui_apt_dependencies | list }}"
    state: present
      
- name: Install FreeTAKServer-UI
  block:
    - name: Clone FreeTAKServer-UI repository
      git:
        repo: "{{ fts_ui_repo_url }}"
        dest: "{{ fts_ui_repo_path }}"
        version: "v{{ fts_ui_version }}"
        force: true

    - name: Install FreeTAKServer-UI
      pip:
        name: "{{ fts_ui_repo_path }}"
        executable: "{{ pip3 }}"

  when: result.stdout | length == 0
