---
- name: Workaround to allow release-info to change for APT repositories
  command: apt-get update -y --allow-releaseinfo-change
  # noqa 303
  when: ansible_os_family == "Debian"
  changed_when: false

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - curl
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm-dev
    - libnss3-dev
    - libssl-dev
    - libsqlite3-dev
    - libreadline-dev
    - libffi-dev
    - libbz2-dev

- name: Download Python 3.8.0
  get_url:
    url: https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tar.xz
    checksum: md5:dbac8df9d8b9edc678d0f4cacdb7dbb0
    dest: /opt

- name: Unarchive Python-3.8.0
  unarchive:
    src: /opt/Python-3.8.0.tar.xz
    dest: /opt
    remote_src: yes
  become: yes

- name: Run Python configure script & build
  command: "{{ item }}"
  args:
    chdir: /opt/Python-3.8.0
  with_items:
    - ./configure --enable-optimizations --enable-loadable-sqlite-extensions
    - make -j {{ ansible_processor_nproc }}
    - make altinstall
  become: yes
  changed_when: false
