---
- name: Hack to update
  command: apt-get --allow-releaseinfo-change update
  # noqa 303
  changed_when: false

- name: Upgrade apt packages
  become: true
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-dev
    - python3-setuptools
    - build-essential
    - python3-gevent
    - python3-lxml
    - libcairo2-dev
    - python3-pip

- name: Install pip dependencies
  pip:
    name: pycairo

- name: Uninstall any previous FreeTAKServer installations
  pip:
    name: FreeTAKServer
    state: absent
    executable: pip3

- name: Install FreeTAKServer
  pip:
    name: FreeTAKServer
    executable: pip3

- name: Enable FreeTAKServer service
  service:
    name: fts
    enabled: yes

- name: Start FreeTAKServer service
  service:
    name: fts
    state: started
