---
- name: Check if FreeTAKServer is installed.
  shell: >
    set -o pipefail &&
    {{ pip3 }} list |
    grep FreeTAKServer
  args:
    warn: no
    executable: /bin/bash
  register: result
  changed_when: false
  ignore_errors: yes

- name: Install FreeTAKServer.
  block:

  - name: Update apt cache.
    apt:
      update_cache: true
      cache_valid_time: 86400
    register: update
    retries: 5
    until: update is success

  - name: Install freetakserver apt dependencies.
    apt:
      name: "{{ fts_apt_dependencies | list }}"
      state: present

  - name: "Install freetakserver pip{{ python3_version }} dependencies."
    pip:
      name: "{{ fts_pip3_dependencies | list }}"
      executable: "pip{{ python3_version }}"

  - name: Clone freetakserver repository.
    git:
      repo: "{{ fts_repo_url }}"
      dest: "{{ fts_repo_path }}"
      version: "v{{ fts_version }}"
      force: true

  - name: Install freetakserver.
    pip:
      name: "{{ fts_repo_path }}"
      executable: "pip{{ python3_version }}"

  when: (result.stdout | length == 0) or fts_force_install
