---
- name: reload freetakserver
  service:
    name: freetakserver
    state: reloaded

- name: enable freetakserver
  service:
    name: freetakserver
    state: "{{ fts_state }}"
    enabled: "{{ fts_enabled }}"
