---
- name: reload freetakserver
  service:
    name: freetakserver
    state: reloaded

- name: enable freetakserver
  service:
    name: freetakserver
    enabled: "{{ fts_enabled }}"

- name: set freetakserver state
  service:
    name: freetakserver
    state: "{{ fts_state }}"
