---
- name: Converge
  hosts: all
  become: yes
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 86400
      register: update
      retries: 5
      until: update is success

    - name: Install netbase to get IP information
      package:
        name: netbase
        state: present
  roles:
    - python3
    - freetakserver
    # - freetakserver-ui
