---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: false
  options:
    vvv: false
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
