---
# fts_ui_install_method: pip
fts_ui_install_method: repo

# custom setup commands
fts_ui_uninstall: false
fts_ui_force_install: false
fts_ui_upgrade: false

# System information
fts_ui_ip_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

# Python configuration
python3_version: 3.8
python3: "/usr/bin/python{{ python3_version }}"
venv_path: "{{ ansible_env.HOME }}/.env"

# FreeTAKServer-UI release information
fts_ui_repo_url: https://github.com/FreeTAKTeam/UI.git
fts_ui_version: 1.9.8

# Set initial service state. 
# Recommended values: `started` or `stopped`.
fts_ui_state: started

# Enable service. 
# Recommended values: `yes` or `no`
fts_ui_enabled: yes 

fts_ui_secret_key: secret_key
