---
- name: Converge
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  tasks:
    - name: Get IPv4
      debug:
        var: ansible_default_ipv4.address
    - name: Include freetakserver
      include_role:
        name: freetakserver
