---
python_version: python3.8
repo_path: /root/FreeTAKServer
venv_path: '{{ repo_path }}/.env'
exec_path: '/usr/local/lib/{{ python_version }}/dist-packages/FreeTAKServer'
connection_message: 'FreeTAKServer'
