---
python_version: python3.8
repo_path: /root/FreeTAKServer
venv_path: '{{ repo_path }}/.env'
exec_path: '{{ venv_path }}/lib/{{ python_version }}/site-packages/FreeTAKServer-1.9.8-py3.8.egg/FreeTAKServer'
connection_message: 'FreeTAKServer'
