---
dependencies:
  - dfl_technology.common
galaxy_info:
  namespace: dfl_technology
  role_name: python3
  author: jonaugustine
  description: Python 3 Ansible Role
  company: DFL-Technology
  license: license (EPL-2.0)
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - python
    - python3
