---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"

defaults:
  run:
    working-directory: 'dfl_technology.ansible-collection-freetakserver'

jobs:

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the codebase.
  #       uses: actions/checkout@v2
  #       with:
  #         path: 'dfl_technology.ansible-collection-freetakserver'

  #     - name: Set up Python 3
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'

  #     - name: Install test dependencies.
  #       run: pip install yamllint

  #     - name: Lint code.
  #       run: |
  #         yamllint .

  molecule:
    name: Molecule Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro: 
          - ubuntu
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: 'dfl_technology.ansible-collection-freetakserver'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip install ansible molecule[docker] docker

      - name: Run Molecule test on Ubuntu 18.04
        run: MOLECULE_DISTRO=ubuntu1804 molecule test 
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Run Molecule test on Ubuntu 20.04
        run: MOLECULE_DISTRO=ubuntu2004 molecule test 
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'